name: flutter_inner_drawer
description: Inner Drawer is an easy way to create an internal side section (left/right) where you can insert a list menu or other.
version: 1.0.0+1
author: Antonino Di Natale <gyorgio88@gmail.com>
homepage: https://github.com/Dn-a/flutter_inner_drawer

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
